module Error =
  List.map_v0 [ 1; 2; 3; 4; 5 ] (fun x y -> x) = Test.runtimeError
    "Expected 2 arguments, got 1"

  Option.map2_v0
    (PACKAGE.Darklang.Stdlib.Option.Option.Just 10)
    "not an option"
    (fun (a, b) -> "1") = Test.runtimeError
    "Option.map2's 2nd argument (`option2`) should be a PACKAGE.Darklang.Stdlib.Option.Option<'b>. However, a String (\"not an...) was passed instead.\n\nExpected: (option2: PACKAGE.Darklang.Stdlib.Option.Option<'b>)\nActual: a String: \"not an option\""

  // Check we get previous errors before later ones
  (List.map_v0 [ 1; 2; 3; 4; 5 ] (fun x -> Test.runtimeError "X"))
  |> List.fakeFunction = Test.runtimeError "X"

module ErrorPropagation =
  type EPRec = { i: Int; m: Int; j: Int; n: Int }
  List.head (Test.runtimeError "test") = Test.runtimeError "test"
  (if Test.runtimeError "test" then 5 else 6) = Test.runtimeError "test"
  (List.head (Test.runtimeError "test")).field = Test.runtimeError "test"
  [ 5; 6; List.head (Test.runtimeError "test") ] = Test.runtimeError "test"
  [ 5; 6; Test.runtimeError "test" ] = Test.runtimeError "test"

  EPRec
    { i = Test.runtimeError "1"
      m = 5
      j = List.head (Test.runtimeError "2")
      n = 6 } = Test.runtimeError "1"

  5 |> (+) (Test.runtimeError "test") |> (+) 3564 = Test.runtimeError "test"
  5 |> (+) (Test.runtimeError "test") = Test.runtimeError "test"
  ("test" |> Test.runtimeError) = Test.runtimeError "test"

  PACKAGE.Darklang.Stdlib.Option.Option.Just(Test.runtimeError "test") = Test.runtimeError
    "test"

  PACKAGE.Darklang.Stdlib.Result.Result.Error(Test.runtimeError "test") = Test.runtimeError
    "test"

  PACKAGE.Darklang.Stdlib.Result.Result.Ok(Test.runtimeError "test") = Test.runtimeError
    "test"


  // pipe into error
  ("test" |> Test.runtimeError |> (++) "3") = Test.runtimeError "test"